apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-charts-backend
  namespace: item-charts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: item-charts-backend
  template:
    metadata:
      labels:
        app: item-charts-backend
    spec:
      containers:
        - name: backend
          image: ${DOCKER_USERNAME}/item-api:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          envFrom:
            - configMapRef:
                name: item-charts-config
