apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-charts-frontend
  namespace: item-charts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: item-charts-frontend
  template:
    metadata:
      labels:
        app: item-charts-frontend
    spec:
      containers:
        - name: frontend
          image: item-frontend:latest
          ports:
            - containerPort: 3000
