apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: item-charts
data:
  nginx.conf: |
    events { }
    http {
      upstream backend {
        server item-charts-backend:8080;
      }      
      server {
        listen 80;
    
        location /api {
          proxy_pass http://backend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
    
        location / {
          proxy_pass http://item-charts-frontend:3000/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
