name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      - name: Run tests
        run: npm test
        working-directory: ./frontend

  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17 for Backend
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set execute permission for gradlew
        run: chmod +x ./backend/gradlew

      - name: Build backend
        run: ./gradlew clean build
        working-directory: ./backend

  dockerize-backend:
    needs: build-backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image for backend
        run: |
          IMAGE_TAG=backend-${{ github.sha }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/item-api:$IMAGE_TAG ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/item-api:$IMAGE_TAG

  deploy-backend:
    needs: dockerize-backend
    uses: Guarionex/aws-deploy-workflow/.github/workflows/deploy.yml@main
    with:
      IMAGE_TAG: backend-${{ github.sha }}
      REPOSITORY_NAME: item-api
      K8S_MANIFESTS_PATHS: k8s/backend-deployment.yaml,k8s/backend-service.yaml,k8s/namespace.yaml,k8s/postgresql.yaml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

  dockerize-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image for frontend
        run: |
          IMAGE_TAG=frontend-${{ github.sha }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/item-frontend:$IMAGE_TAG ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/item-frontend:$IMAGE_TAG

  deploy-frontend:
    needs: dockerize-frontend
    uses: Guarionex/aws-deploy-workflow/.github/workflows/deploy.yml@main
    with:
      IMAGE_TAG: frontend-${{ github.sha }}
      REPOSITORY_NAME: item-frontend
      K8S_MANIFESTS_PATHS: k8s/frontend-deployment.yaml,k8s/frontend-service.yaml,k8s/namespace.yaml,k8s/postgresql.yaml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
